### ISSUE TITLE
[BUG] update 0.214.2

### ISSUE THREAD

**Issue by awdwyn** [Vodianoi/QuickPingMod#104]
### **Describe the bug**
The mod fails to create pings and errors to console after the latest Valheim patch.

### **To Reproduce**
1. Update Valheim
2. Press either hotkey to create a ping

### **Expected behavior**
The ping should be created, and optionally a map marker.

### **Additional context**
**_[Error  : Unity Log] MissingFieldException: Field 'Chat/WorldTextInstance.m_textField' not found.
Stack trace:
(wrapper dynamic-method) Chat.DMD<Chat::AddInworldText>(Chat,UnityEngine.GameObject,long,UnityEngine.Vector3,Talker/Type,UserInfo,string)
Chat+<>c__DisplayClass12_0.<OnNewChatMessage>b__2 (Fishlabs.Core.Data.Profile profile) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
UserInfo+<>c.<.cctor>b__15_0 (PrivilegeManager+User user, System.Action`1[T] callback) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
Chat+<>c__DisplayClass12_0.<OnNewChatMessage>b__1 () (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
Chat.OnCanCommunicateWithResult (PrivilegeManager+Result access, System.Action displayChatMessage) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
Chat+<>c__DisplayClass12_0.<OnNewChatMessage>b__0 (PrivilegeManager+Result access) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
PrivilegeManager.CanAccess (PrivilegeManager+Permission permission, System.String platformUser, CanAccessResult canAccessResult) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
PrivilegeManager.CanCommunicateWith (System.String user, CanAccessResult canCommunicateWithResult) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
Chat.OnNewChatMessage (UnityEngine.GameObject go, System.Int64 senderID, UnityEngine.Vector3 pos, Talker+Type type, UserInfo user, System.String text, System.String senderNetworkUserId) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
(wrapper dynamic-method) Chat.DMD<Chat::RPC_ChatMessage>(Chat,long,UnityEngine.Vector3,int,UserInfo,string,string)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
RoutedMethod`5[T,U,V,B,K].Invoke (System.Int64 rpc, ZPackage pkg) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, System.String methodName, System.Object[] parameters) (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
QuickPing.Patches.Player_Patch.SendPing (UnityEngine.Vector3 position, System.String text, System.Boolean local) (at <73e7d0d1b5ae4a2bae19a5a1ed395e82>:0)
QuickPing.Patches.Player_Patch.SendPing (QuickPing.HoverObject ping) (at <73e7d0d1b5ae4a2bae19a5a1ed395e82>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
QuickPing.Patches.Player_Patch.Player_Update (Player __instance) (at <73e7d0d1b5ae4a2bae19a5a1ed395e82>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)_**

**Comment by Vodianoi** [comment]
Thanks for reporting,this is due to the 13/03 update, will update the mod soon too !
