### ISSUE TITLE
[BUG] Indestructible trees and rocks

### ISSUE THREAD

**Issue by HughODwyer90** [Vodianoi/QuickPingMod#108]
**Description**
Fallen trees, stumps, rocks, shrubs, saplings are indestructible.
Damage registers as I can see the damage done numbers, but the listed terrain is not destroyed.

**To Reproduce**
1. Install mod
2. Run game
3. Attack one of the listed items with an appropriate weapon.

**Expected behavior**
The listed terrain eventually is destroyed and resources gatherable.

**Comment by Vodianoi** [comment]
Last update broke my detection of destroyable objects.
I'll update to last version soon !

**Comment by m-wulff** [comment]
I'm still getting used to how GitHub works, but as I understand it this bugfix is now complete, correct? Would you be able to upload the patch on Nexus? If not, is there a way for me to download it through GitHub so I can start playing with this mod enabled again?

**Comment by Vodianoi** [comment]
Hey, I fixed this bug but there are still other problems with the last update so I did not upload it to Nexus yet. You can still download the last version from Github with this dix but you won't be able to rename pins.

I'll try to fix other problems asap

**Comment by m-wulff** [comment]
Great, thanks!

**Comment by misodonkatsu** [comment]
I had same issue. glad to see it will get fixed

**Comment by astranberg** [comment]
Does the hotfix work? Can this be merged?
