### ISSUE TITLE
[BUG] Mod is completely unusable with new update (0.217.14)

### ISSUE THREAD

**Issue by DariusWolfe** [Vodianoi/QuickPingMod#111]
**Describe the bug**
This mod is very much broken with the new update (0.217.14). Console spits out a lot of red whenever you attempt to ping or mark via hotkeys, and pings and pins do not appear. Doesn't seem to have any other side-effects, aside from it simply not working.

**Comment by BurroTile** [comment]
Same here on 0.217.14. Great Mod and thank you!

[Error  : Unity Log] MissingMethodException: long ZDOID.get_userID()
Stack trace:
QuickPing.Patches.Player_Patch.SendPing (QuickPing.HoverObject ping) (at <58070dd06e7b4d03a1ee0a4c41ebbcfc>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <80fe1a4e36fe44618284312cb721a597>:0)
QuickPing.Patches.Player_Patch.Player_Update (Player __instance) (at <58070dd06e7b4d03a1ee0a4c41ebbcfc>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
