### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kherae** [Vodianoi/QuickPingMod#115]
**Describe the bug**
mod prevents right click from removing pins from map
**To Reproduce**
enable this mod and no other (will result in bepinex, jotunn and this mod being loaded). load game. right click pin.

**Additional context**
```
[Error  : Unity Log] MissingMethodException: Method not found: Minimap/PinData .Minimap.GetClosestPin(UnityEngine.Vector3,single)
Stack trace:
(wrapper dynamic-method) Minimap.DMD<Minimap::RemovePin>(Minimap,Minimap/PinData)
Minimap.RemovePin (UnityEngine.Vector3 pos, System.Single radius) (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.OnMapRightClick (UIInputHandler handler) (at <da52c09f594f4a7480000b7420815ba7>:0)
UIInputHandler.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <256a5619bba44d0eb1f0a92f595de63d>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <a01fe238487248d39ba352ec152ec890>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <a01fe238487248d39ba352ec152ec890>:0)
UnityEngine.EventSystems.EventSystem:Update()
```

**Comment by astranberg** [comment]
This might be related?

When I press `T` or `G`, the item is pinged but no pins are placed in the map. I see this error in the console:

`[Error  : Unity Log] MissingMethodException: Method not found: Minimap/PinData .Minimap.GetClosestPin(UnityEngine.Vector3,single)
Stack trace:
(wrapper dynamic-method) Minimap.DMD<Minimap::RemovePin>(Minimap,Minimap/PinData)
Minimap.UpdateShoutPins () (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.UpdateDynamicPins (System.Single dt) (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.Update () (at <da52c09f594f4a7480000b7420815ba7>:0)

[Error  : Unity Log] MissingMethodException: Method not found: Minimap/PinData .Minimap.GetClosestPin(UnityEngine.Vector3,single)
Stack trace:
(wrapper dynamic-method) Minimap.DMD<Minimap::RemovePin>(Minimap,Minimap/PinData)
Minimap.UpdateShoutPins () (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.UpdateDynamicPins (System.Single dt) (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.Update () (at <da52c09f594f4a7480000b7420815ba7>:0)

[Error  : Unity Log] MissingMethodException: Method not found: Minimap/PinData .Minimap.GetClosestPin(UnityEngine.Vector3,single)
Stack trace:
(wrapper dynamic-method) Minimap.DMD<Minimap::RemovePin>(Minimap,Minimap/PinData)
Minimap.UpdateShoutPins () (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.UpdateDynamicPins (System.Single dt) (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.Update () (at <da52c09f594f4a7480000b7420815ba7>:0)`

I also cannot add pins directly in the map.

The only mods I have installed are:

- BepInExPack_Valheim v5.4.2202 by denikson
- Jotunn v2.19.1 by ValheimModding
- QuickPing v1.5.10 by Atopy

All via r2modman. On Valheim 0.217.46 (n-23)

**Comment by Vodianoi** [comment]
Yep, update 0.217.46 (10/04) broke the mod, I'll try to update it during the week if Valheim references are updated too
Thank you for reporting !

**Comment by Kherae** [comment]
it appears fixed with the recent update. other confirmations?

**Comment by Vodianoi** [comment]
Yep fixed for now
