### ISSUE TITLE
[BUG] Existing pins hidden when first installed

### ISSUE THREAD

**Issue by dharkness** [Vodianoi/QuickPingMod#119]
**Describe the bug**

I installed the mod locally with no other pin-related mods installed. When I loaded into my server, all of my current pints were hidden but thankfully not deleted. Once I uninstalled the mod and reconnected, my pins returned.

While this would be fine in a new world, I have a ton of pins already that I don't want to lose.

**To Reproduce**

1. Launch the game without the mod.
2. Add pins to the world.
3. Exit and install the mod.
4. Relaunch the game.

**Expected behavior**

You see the pins you added without the mod.

**Actual behavior**

The map has no pins. Hopefully, no screenshot needed for that. :)

**Additional context**

Thunderstore profile code for the mods I have installed: `018f0372-1733-97d9-5f92-c122babcf946`

**Comment by Vodianoi** [comment]
Hey! I checked your modpack : it seems like you're using "QuickPing_Revived", not QuickPing.
Try last version of QuickPing (1.5.11)

https://thunderstore.io/c/valheim/p/Atopy/QuickPing/
or 
https://www.nexusmods.com/valheim/mods/2033

**Comment by dharkness** [comment]
My bad, the "Revived" page pointed here. I assumed it was the same repo.

I installed this mod instead, and indeed my pints remained on launch.

Thanks!
