### ISSUE TITLE
[BUG] Keybinds not changing to the one I set (the default keybind is being kept instead)

### ISSUE THREAD

**Issue by DaveKX** [Vodianoi/QuickPingMod#38]
//Edited in order to not confuse whoever sees this, the bug is in the comments section

Here is how the mod is configured
![image](https://user-images.githubusercontent.com/90359076/208197270-b44b1e6b-f200-4be8-8efd-bf73e9a0b78e.png)

**Comment by DaveKX** [comment]
Well actually just discovered that this is not what is happening. What is happening is: my configs are set to 'None' and 'G', and the default values for those are 'G' and 'T', respectively. However, the behavior I'm getting is that apparently it is still set to 'G' and 'T', even after I replacing them and restarting the game... So the 'PingInputKey' actually is working correctly, but the keybinds are not being changed

**Comment by Vodianoi** [comment]
Hey, thanks for reporting!

It seems there are still issues with the Input system...

I should also make a better setting config, names aren't really clear.

I'll fix that for 1.5.4 !

**Comment by DaveKX** [comment]
Thank you! I changed the title and the post to all of this be clearer!
