### ISSUE TITLE
[BUG] Conflict with Advize_PlantEverything

### ISSUE THREAD

**Issue by RequiemOfSilence** [Vodianoi/QuickPingMod#58]
Won't create pin using T (Ping is working fine)on Berrys Dandelions Tin Copper etc. 
Forced Ping does work fine.
No changes done.
Tried several New Worlds/Chars.
Deactivated all other mods.
Unable to find the issue.
Need help :c

**Comment by Vodianoi** [comment]
Hey ! Here are a few things you can try :

1. Make sure you have the latest version of the mod (version 1.5.3).
2. Check your settings to see if the "AddPin" option is enabled.
3. You might try deleting the config file (`Bepinex/config/com.atopy.plugins.quickping.cfg`) and starting the game again.
4. If none of these steps work, send me the log file (located at `Bepinex/LogOutput.log`) from a session where you tried to add pins.

**Comment by RequiemOfSilence** [comment]
Version checked its 1.5.3
Setting: AddPin = enabled
Deleted the folder now error still ocures.
now trying to deactivate and reactivate the setting. Did not helped.
Can sadn one with only your mod enabled
Sending Log
[LogOutput.log](https://github.com/Vodianoi/QuickPingMod/files/10356474/LogOutput.log)

**Comment by Vodianoi** [comment]
Yes please send me te log without any mods. ValheimPlus is a pretty heavy mod, didn't test with it.

This log in `C:\Users\[USERNAME]\AppData\LocalLow\IronGate\Valheim\Player.log`

**Comment by RequiemOfSilence** [comment]
Interesting now disabled all mods again this time it worked fine
Trying to reenable other mods = does not work
All mods beside your mod deactivated again = working fine again
Now trying to add mods one by one.
BepInExPack_Valheim by denikson = worked
CraftBuildSmeltCookFuelPullFromContainers by Lysbell = worked
PlantEverything by Advize = does not work for berrys/tin worked 
ExtendedItemDataFramework by RandyKnapp = worked
EquipmentAndQuickSlots by RandyKnapp = worked
ValheimPlus = worked

so someting seems to be incompatible with PlantEverything

only starting game with both mod active and sending log
[Player.log](https://github.com/Vodianoi/QuickPingMod/files/10360852/Player.log)
does not work for berrys,mushrooms/tin worked
not more testing done
Able to test more later

**Comment by RequiemOfSilence** [comment]
did not tested tin before only berrys

**Comment by RequiemOfSilence** [comment]
Mushrooms arent supported at all right?

**Comment by Vodianoi** [comment]
Ok thank you for the details !

Seems like PlantEverything change how berries (and all plants I think) are named/identified. The pin should work for Dungeons, Ores, Fires, Dragon eggs and portals. And for lot more with G.

Now that I know it is a conflict with PlantEverything, I will try to understand why and make a fix



> shrooms arent supported at all right?

Nope, some plants aren't detected yet, not the same collider

**Comment by RequiemOfSilence** [comment]
Idk if this should stand here but,
I would highly like mushrooms thistle etc to work.
I realy appreciate your work.
Good luck and have a nice day :)
