### ISSUE TITLE
Force Map Pin button -enhancement

### ISSUE THREAD

**Issue by HabDand** [Vodianoi/QuickPingMod#9]
Using this with no map (but can open map at cartography table). 
Mod currently adds map pings for some items. Can we have a keypress (Ctrl or shift plus ping button) that forces a map pin to be created on the quick ping spot. Map pin created doesn't have to be particularly interesting or have text (maybe an "!"). The simple ball/circle pin is fine unless you want to go wild with custom pin.

Bonus stretch goal...
Any chance this mod can add some further pin shapes we can use in map manually?

**Comment by Vodianoi** [comment]
Hey !

**Comment by HabDand** [comment]
Ah cool, I saw the ping everything enhancement but as it was a note for yourself it wasnt clear. I assumed it was gong to be auto map pins everything around you. But l now get the sense that you are definitely NOT going to auto-pin anything so l am happy! :)

**Comment by Vodianoi** [comment]
https://github.com/Vodianoi/QuickPingMod/issues/7
