### ISSUE TITLE
[ENHANCEMENT] Pin visible for other players?

### ISSUE THREAD

**Issue by RequiemOfSilence** [Vodianoi/QuickPingMod#92]
Hey thank you very much for the update :) 
Pings and pins work fine marking every pickable <3
but on multiplayer pins seems not to be visible for my mate.
Its not a dedicated server, just world opened as server.
My question is should it be visible or isnt it implemented that the pin is set for both.

Thank you in advance. :)

**Comment by RequiemOfSilence** [comment]
oh than its alright. :D
pins on catographer works fine.
Also if i reload the game the marker resets it set name 
example: Raspberry Bush swaped to "B" now again "Raspberry Bush"
Destroyed with attack did not disapeared (tested on reloaded game not on placed and then destroyed)

**Comment by Vodianoi** [comment]
Hm, there's something with the save/load then. 
Where is your save located (in the save menu in game, there's an icon on the left of each save) ? 
Does this happen only for you or to your mate too ? Maybe only to your mate ?

**Comment by RequiemOfSilence** [comment]
Tested on same load of the world the destroy pin works fine.
Tested if Name save casued this issue.
Seems not to be the case.

**Comment by Vodianoi** [comment]
Ok then it's on my todo list. For now the mod doesn't make difference between server and client
https://github.com/Vodianoi/QuickPingMod/issues/11

**Comment by RequiemOfSilence** [comment]
Destroy ping works only for one person. Sometimes its for me sometomes for my mate we are testing if we find the reason why its loke this

for plants planted by  plant everything mod seems to work like the following:
Person who panted = the pin destroyed

For natural spawned only works for one person. Mostly its not working for the server host :o

Hope you are not irritated by my testing. :)

**Comment by Vodianoi** [comment]
> Hope you are not irritated by my testing. :)

Actually this is very helpful !
Workin on it for next patch

**Comment by RequiemOfSilence** [comment]
Then i do my best and provide every information i can find.
